# Generated by Django 3.1.2 on 2021-02-25 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactus',
            new_name='contact',
        ),
    ]
