# Generated by Django 3.1.7 on 2021-04-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210225_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imgsave1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('file1', models.FileField(upload_to='')),
                ('value', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'img',
            },
        ),
    ]
