# Generated by Django 3.1.7 on 2021-04-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_imgsave1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgsave1',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
